// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_166b6ITizX0Q8vnCKWoi3Pk9AymS_L8',
    appId: '1:352167935210:web:fe165225185eea03c66b93',
    messagingSenderId: '352167935210',
    projectId: 'my-learning-plan',
    authDomain: 'my-learning-plan.firebaseapp.com',
    storageBucket: 'my-learning-plan.firebasestorage.app',
    measurementId: 'G-XVQ4E1881X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIYEVxP6Cy2zDyf8UU3uF4TlOvAitULr0',
    appId: '1:352167935210:android:7ff8659f31c907eac66b93',
    messagingSenderId: '352167935210',
    projectId: 'my-learning-plan',
    storageBucket: 'my-learning-plan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO78ag3AL309YipnLe-6qC66dqAjYaeSc',
    appId: '1:352167935210:ios:40a75d3aca5640eac66b93',
    messagingSenderId: '352167935210',
    projectId: 'my-learning-plan',
    storageBucket: 'my-learning-plan.firebasestorage.app',
    iosBundleId: 'com.example.myLearningPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO78ag3AL309YipnLe-6qC66dqAjYaeSc',
    appId: '1:352167935210:ios:40a75d3aca5640eac66b93',
    messagingSenderId: '352167935210',
    projectId: 'my-learning-plan',
    storageBucket: 'my-learning-plan.firebasestorage.app',
    iosBundleId: 'com.example.myLearningPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_166b6ITizX0Q8vnCKWoi3Pk9AymS_L8',
    appId: '1:352167935210:web:92fab1a281637c46c66b93',
    messagingSenderId: '352167935210',
    projectId: 'my-learning-plan',
    authDomain: 'my-learning-plan.firebaseapp.com',
    storageBucket: 'my-learning-plan.firebasestorage.app',
    measurementId: 'G-763NDR81BJ',
  );
}
